### ISSUE TITLE
Overflow of Logarithm (or other transform) with local property spline

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/AtomDB#2]
@gabrielasd and @msricher do we have something to control for the fact that the log of the atomic density/orbital energy/orbital densities may fail when the argument of the log is too close to zero? Something like: 
    https://github.com/theochem/denspart/blob/e21de342078035669832b693cb49b269870a6e02/denspart/vh.py#L434

_Originally posted by @PaulWAyers in https://github.com/theochem/AtomDB/discussions/1_

**Comment by gabrielasd** [comment]
@msricher I signed this to you since you mentioned you were planing to modify the `cubic_interp` function. But let me know if this is not a change you were planing for this release
https://github.com/theochem/AtomDB/blob/85031c5fc08b7c920a093c84ab4f6458b5d48825/atomdb/api.py#L446

**Comment by msricher** [comment]
@PaulWAyers I can implement that technique here. @gabrielasd do we have any cases currently where we know it fails?

**Comment by gabrielasd** [comment]
> @PaulWAyers I can implement that technique here. @gabrielasd do we have any cases currently where we know it fails?

No, I haven't come across any warnings or errors associated to it in the tests or examples I've ran.

For example taking the log of one of the last elements in the density array for Nitrogen (from gaussian dataset) works doesn't raise an error:
`np.log([2.58740145e-37]) # array([-84.24499437]) `

but this `np.log([0.])` does: RuntimeWarning

So maybe, we have been just lucky to not encounter any hard zero density properties. (I'm not sure what threshold NumPy has for this, since e-37 is very much zero to me)

**Comment by PaulWAyers** [comment]
OK, based on this I think it is fair to just close this issue until/unless it rears its ugly head. The discussion will be here in case, in the future, we need it. 

My main worry would be with what happens when splining (or otherwise processing) a log(density) like this. But it is easy/robust to just truncate splines for such points.
