### ISSUE TITLE
Update GBasis API in compilation scripts

### ISSUE THREAD

**Issue by gabrielasd** [theochem/AtomDB#20]
This affects the datasets that rely on method using gaussian basis sets, the UHF (gaussian) and the HCI datasets.

**Comment by Aditish51** [comment]
Hey, @gabrielasd  I would like to try and  solve this issue. Can you please provide me more details on it?

**Comment by Ansh-Sarkar** [comment]
Hi @gabrielasd . I ran into the same issue recently while I was working on adding the METADATA support to the available datasets. Have been working on it for a while : #15. There are a few libraries that I had to build from source, namely - `gbasis`, `iodata`, and `grid`. Also while building the sphinx documentation, the necessary theme dependencies were not present.

## Proposed Solutions
- [ ] In order to improve the Developer Experience (DX) and enable a swift setup I was thinking if we might try to create a developer environment setup script that could essentially take care of all the additional dependencies and their installation ?

- [ ] For the sphinx theme dependencies, even though they have been defined under the [optional dependencies section](https://github.com/theochem/AtomDB/blob/968ebf1e48de37af1dd3c20a67263184b66e24a7/pyproject.toml#L60) would it be a good idea to have something like a `requirements.dev.txt` file for easy installation for developers ? Not sure if that is a good idea. If we did have one though, we could use that in the setup script I was referring to in point 1.

**Comment by gabrielasd** [comment]
Hi @Ansh-Sarkar, 
I think both are very good ideas and great feedback.
@msricher what do you think?

I'm not sure if a separate setup script or just adding a dev section to the configuration toml is the way to go here, though.
At the very least we need to improve the documentation for installation instructions, which we will be working on soon.

**Comment by msricher** [comment]
I think just adding it to the toml file if good enough.

**Comment by Ansh-Sarkar** [comment]
Thank you @gabrielasd and @msricher . I agree that adding a `[dev]` section to the toml file would be a better idea. Will allow keeping all dependencies in a single file.

Also about the documentation for the installation instructions I was thinking we could maybe add a quickstart section to the Sphinx documentation as well as the project readme. Would love to work on that once #15 is taken care of. In fact, would love to hear your feedback regarding my current progress on #15 as well, whenever time permits. Thanks !

**Comment by gabrielasd** [comment]
This issue has been resolved in the current version on master.
