### ISSUE TITLE
Atomic radii and other properties

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/AtomDB#5]
We should make sure we have the atomic radii and other properties in 
https://github.com/QC-Devs/gopt/blob/main/gopt/periodic/data/elements.csv

**Comment by gabrielasd** [comment]
Place the multiplicities and elements tuples in same file
https://github.com/theochem/AtomDB/blob/184a6933cc61cdca965a6cc2806ea2168415d543/atomdb/api.py#L80
https://github.com/theochem/AtomDB/blob/184a6933cc61cdca965a6cc2806ea2168415d543/atomdb/api.py#L63

**Comment by gabrielasd** [comment]
We need to compare the MULTIPLICITIES table for the ground state multiplicities against another source to make sure it is correct. It was generated from Derrick's HDF5 file.

**Comment by PaulWAyers** [comment]
You can double-check against 
https://en.wikipedia.org/wiki/Term_symbol#Atomic_term_symbols_of_the_chemical_elements

I know that there are some issues, at least for excited states, from the automatic parsing. For example, for [Pd](https://physics.nist.gov/cgi-bin/ASD/energy1.pl?de=0&spectrum=pd+0&submit=Retrieve+Data&units=0&format=0&output=0&page_size=15&multiplet_ordered=0&conf_out=on&term_out=on&level_out=on&unc_out=1&j_out=on&lande_out=on&perc_out=on&biblio=on&temp=), the first triplet is only $6564.148 \text{ cm}^{-1}$ above the ground state, but I think we missed it because it is only labelled with $J$ quantum numbers. I think the data is pretty good up to Sr ($Z=38$).

**Comment by marco-2023** [comment]
Hello @gabrielasd and @PaulWAyers:
I made a version of the new `periodic` module for `atomdb` and checking the multiplicities I stumbled into a problem:
As it has been implemented so far, when the multiplicity is wanted for an atom of Z=`atnum` with a given `charge`, the module returns the multiplicity of the element with `number of electrons` = `Z` - `charge`. The problem is there are elements for which this is not correct. 

For example:
For Cr its electron configuration is [Ar] $4s^{1}3d^{5}$ and according to this algorithm for Cr $^+$ its multiplicity is taken equal to the one for V with electronic configuration [Ar]$4s^{2}3d^{3}$  [(multiplicity = 4)](https://physics.nist.gov/cgi-bin/ASD/ie.pl?spectra=V&submit=Retrieve+Data&units=1&format=0&order=0&at_num_out=on&sp_name_out=on&ion_charge_out=on&el_name_out=on&seq_out=on&shells_out=on&level_out=on&ion_conf_out=on&e_out=0&unc_out=on&biblio=on) but the real electron configuration of Cr $^+$ is [Ar] $3d^{5}$  [(multiplicity = 6)](https://physics.nist.gov/cgi-bin/ASD/ie.pl?spectra=Cr&submit=Retrieve+Data&units=1&format=0&order=0&at_num_out=on&sp_name_out=on&ion_charge_out=on&el_name_out=on&seq_out=on&shells_out=on&level_out=on&ion_conf_out=on&e_out=0&unc_out=on&biblio=on).

This kind of deviation is also potentially expected for multi charged atoms. Do you have any sugestions on how to deal with it? I think making a database for each atom multiplicity may be excessive.

**Comment by gabrielasd** [comment]
@marco-2023 thanks for bringing this issue up. It is definitely a problem present in the `numeric` dataset, and something to check/test in the others.

There is one database that has the information like you suggest. It is the file `database_beta_1.3.0.h5` which has all stable multiplicities for a given atomic number and charge. So I think for neutral and cations this is what we should be using to check against in the scripts. For example as is done for the NIST dataset:
https://github.com/theochem/AtomDB/blob/edd460414fa05df870d1776b38b22386a1236d72/atomdb/datasets/nist/__init__.py#L79-L86

However, for the anions, we are just taking the value from the isoelectronic specie, and we have the same problem you describe (the anion of V gets assigned the multiplicity from neutral Cr)
